#!/bin/bash
SSID=$(iwgetid -r)
ENABLED=$(nmcli radio wifi | grep enabled)
CONNECTED=$(nmcli connection show --active | grep wlp3s0)

if [ $ENABLED ]
then
    if [[ $CONNECTED ]]
    then
        STRENGTH=$(awk 'NR==3 {print $3}' /proc/net/wireless | sed -e 's/\.//')
        PERCENTAGE=$(echo "$STRENGTH"*100/70 | bc)
        echo "  $PERCENTAGE%"
    else
        echo "  No Wifi"
    fi
elif [ ! $ENABLED ]
then
    echo "  Airplane Mode"
    separator_block_width=3
fi

case $BLOCK_BUTTON in
	1) termite -e nmtui ;;
	3) sh ~/dotfiles/scripts/i3blocks/toggle_wifi.sh ;;
esac
